# Generated by Django 5.2.3 on 2025-06-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('total_records', models.IntegerField(verbose_name='总记录数')),
                ('success_records', models.IntegerField(verbose_name='成功记录数')),
                ('error_records', models.IntegerField(verbose_name='错误记录数')),
                ('import_time', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
                ('errors', models.TextField(blank=True, verbose_name='错误信息')),
            ],
            options={
                'verbose_name': '导入日志',
                'verbose_name_plural': '导入日志',
                'db_table': 'import_log',
                'ordering': ['-import_time'],
            },
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=20, unique=True, verbose_name='学号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('id_card', models.CharField(max_length=18, unique=True, verbose_name='身份证号')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('gz_student_id', models.CharField(max_length=30, unique=True, verbose_name='广州学籍号')),
                ('national_student_id', models.CharField(max_length=30, unique=True, verbose_name='全国学籍号')),
                ('household_address', models.TextField(verbose_name='户籍所在地')),
                ('living_address', models.TextField(verbose_name='居住所在地')),
                ('guardian_father', models.CharField(max_length=50, verbose_name='监护人(父亲)')),
                ('guardian_mother', models.CharField(max_length=50, verbose_name='监护人(母亲)')),
                ('guardian_father_phone', models.CharField(max_length=20, verbose_name='监护人(父亲)电话')),
                ('guardian_mother_phone', models.CharField(max_length=20, verbose_name='监护人(母亲)电话')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '学生数据',
                'verbose_name_plural': '学生数据',
                'db_table': 'student_data',
                'ordering': ['-created_at'],
            },
        ),
    ]
