# Generated by Django 5.2.3 on 2025-06-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='guardian_father',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='监护人(父亲)'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='guardian_father_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='监护人(父亲)电话'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='guardian_mother',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='监护人(母亲)'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='guardian_mother_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='监护人(母亲)电话'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='household_address',
            field=models.TextField(blank=True, null=True, verbose_name='户籍所在地'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='living_address',
            field=models.TextField(blank=True, null=True, verbose_name='居住所在地'),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='national_student_id',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='全国学籍号'),
        ),
    ]
