# Generated by Django 5.2.3 on 2025-06-24 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0002_alter_studentdata_guardian_father_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='national_student_id',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='全国学籍号'),
        ),
    ]
