# Generated by Django 5.2.3 on 2025-06-26 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0003_alter_studentdata_national_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='class_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='班级'),
        ),
        migrations.AddField(
            model_name='studentdata',
            name='grade',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='年级'),
        ),
    ]
