# Generated by Django 5.2.3 on 2025-06-26 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0004_studentdata_class_name_studentdata_grade'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transfer_type', models.CharField(choices=[('transfer_in', '转入'), ('transfer_out', '转出')], max_length=20, verbose_name='转学类型')),
                ('transfer_date', models.DateField(verbose_name='转学日期')),
                ('transfer_reason', models.TextField(verbose_name='转学原因')),
                ('previous_school', models.CharField(blank=True, max_length=100, null=True, verbose_name='原学校')),
                ('target_school', models.CharField(blank=True, max_length=100, null=True, verbose_name='目标学校')),
                ('transfer_grade', models.CharField(blank=True, max_length=10, null=True, verbose_name='转入年级')),
                ('transfer_class', models.CharField(blank=True, max_length=20, null=True, verbose_name='转入班级')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已批准'), ('rejected', '已拒绝'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='处理状态')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('processor', models.CharField(blank=True, max_length=50, null=True, verbose_name='处理人')),
                ('process_time', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_records', to='student_data.studentdata', verbose_name='学生')),
            ],
            options={
                'verbose_name': '转学记录',
                'verbose_name_plural': '转学记录',
                'db_table': 'transfer_record',
                'ordering': ['-created_at'],
            },
        ),
    ]
