# Generated by Django 5.2.3 on 2025-06-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0006_studentdata_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrecord',
            name='approval_notes',
            field=models.TextField(blank=True, null=True, verbose_name='审批意见'),
        ),
        migrations.AddField(
            model_name='transferrecord',
            name='target_class',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='目标班级'),
        ),
        migrations.AddField(
            model_name='transferrecord',
            name='target_grade',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='目标年级'),
        ),
        migrations.AddField(
            model_name='transferrecord',
            name='target_school_address',
            field=models.TextField(blank=True, null=True, verbose_name='目标学校地址'),
        ),
        migrations.AddField(
            model_name='transferrecord',
            name='target_school_contact',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='目标学校联系人'),
        ),
        migrations.AddField(
            model_name='transferrecord',
            name='target_school_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='目标学校联系电话'),
        ),
    ]
