# Generated by Django 5.2.3 on 2025-06-28 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0007_transferrecord_approval_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferrecord',
            name='transfer_type',
            field=models.CharField(choices=[('transfer_in', '转入'), ('transfer_out', '转出'), ('suspend', '休学'), ('resume', '复学')], max_length=20, verbose_name='转学类型'),
        ),
    ]
