# Generated by Django 5.2.3 on 2025-06-28 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0008_alter_transferrecord_transfer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferrecord',
            name='contact_person',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='联系人'),
        ),
        migrations.AddField(
            model_name='transferrecord',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话'),
        ),
        migrations.AddField(
            model_name='transferrecord',
            name='expected_resume_date',
            field=models.DateField(blank=True, null=True, verbose_name='预期复学日期'),
        ),
    ]
