# Generated by Django 5.2.3 on 2025-07-08 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_data', '0009_transferrecord_contact_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='考试名称')),
                ('exam_type', models.CharField(choices=[('midterm', '期中考试'), ('final', '期末考试'), ('monthly', '月考'), ('quiz', '小测'), ('homework', '作业')], max_length=20, verbose_name='考试类型')),
                ('academic_year', models.CharField(max_length=20, verbose_name='学年')),
                ('semester', models.CharField(choices=[('1', '第一学期'), ('2', '第二学期')], max_length=10, verbose_name='学期')),
                ('exam_date', models.DateField(verbose_name='考试日期')),
                ('total_score', models.DecimalField(decimal_places=1, default=100.0, max_digits=5, verbose_name='总分')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布成绩')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
                'db_table': 'exam',
                'ordering': ['-exam_date'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='科目名称')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='科目代码')),
                ('category', models.CharField(choices=[('main', '主科'), ('sub', '副科'), ('elective', '选修课')], default='main', max_length=20, verbose_name='科目类别')),
                ('credit', models.DecimalField(decimal_places=1, default=1.0, max_digits=3, verbose_name='学分')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '科目',
                'verbose_name_plural': '科目',
                'db_table': 'subject',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, max_digits=5, verbose_name='分数')),
                ('rank_in_class', models.IntegerField(blank=True, null=True, verbose_name='班级排名')),
                ('rank_in_grade', models.IntegerField(blank=True, null=True, verbose_name='年级排名')),
                ('remarks', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_data.exam', verbose_name='考试')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='student_data.studentdata', verbose_name='学生')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_data.subject', verbose_name='科目')),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '成绩',
                'db_table': 'grade',
                'ordering': ['-exam__exam_date', 'student__school_id', 'subject__code'],
                'unique_together': {('student', 'subject', 'exam')},
            },
        ),
    ]
